export enum ConfigurationEnum {
  'TAX_PER_KM' = 'TAX_PER_KM',
  'CLASS_OPTIONS' = 'CLASS_OPTIONS',
  'GOOGLE_MAPS_KEY' = 'GOOGLE_MAPS_KEY',
  'ORIGIN_ADDRESS' = 'ORIGIN_ADDRESS',
  'CEP_PROVIDER_API_URL' = 'CEP_PROVIDER_API_URL'
}
